# Generated by Django 5.2.3 on 2025-07-12 04:33

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Notes')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(max_length=500, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('suburb', models.CharField(blank=True, choices=[('MELBOURNE', 'Melbourne'), ('SYDNEY', 'Sydney'), ('BRISBANE', 'Brisbane'), ('PERTH', 'Perth'), ('ADELAIDE', 'Adelaide'), ('GOLD_COAST', 'Gold Coast'), ('NEWCASTLE', 'Newcastle'), ('CANBERRA', 'Canberra'), ('HOBART', 'Hobart'), ('DARWIN', 'Darwin'), ('TOWNSVILLE', 'Townsville'), ('GEELONG', 'Geelong')], max_length=100, verbose_name='Suburb')),
                ('state_territory', models.CharField(blank=True, choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=3, verbose_name='State or Territory')),
                ('postcode', models.CharField(blank=True, max_length=4, verbose_name='Postcode')),
                ('tfn', models.CharField(unique=True, verbose_name='TFN')),
                ('fund_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fund Name')),
                ('abn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ABN')),
                ('member_number', models.IntegerField(blank=True, null=True, verbose_name='Number of Members')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=50, verbose_name='Account Name')),
                ('bsb', models.CharField(max_length=6, unique=True, verbose_name='BSB')),
                ('account_number', models.CharField(max_length=10, unique=True, verbose_name='Account Number')),
                ('emergency_contact_first_name', models.CharField(max_length=20, verbose_name='Emergency Contact First Name')),
                ('emergency_contact_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Last Name')),
                ('emergency_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Emergency Contact Number')),
                ('emergency_contact_home', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Emergency Contact Home')),
                ('emergency_contact_relationship', models.CharField(max_length=20, verbose_name='Emergency Contact Relationship')),
            ],
        ),
    ]
