# Generated by Django 5.2.3 on 2025-07-03 15:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfn', models.CharField(unique=True, verbose_name='TFN')),
                ('fund_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fund Name')),
                ('abn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ABN')),
                ('member_number', models.IntegerField(blank=True, null=True, verbose_name='Number of Members')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=50, verbose_name='Account Name')),
                ('bsb', models.CharField(max_length=6, unique=True, verbose_name='BSB')),
                ('account_number', models.CharField(max_length=10, unique=True, verbose_name='Account Number')),
                ('emergency_contact_first_name', models.CharField(max_length=20, verbose_name='Emergency Contact First Name')),
                ('emergency_contact_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Last Name')),
                ('emergency_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Emergency Contact Number')),
                ('emergency_contact_home', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Emergency Contact Home')),
                ('emergency_contact_relationship', models.CharField(max_length=20, verbose_name='Emergency Contact Relationship')),
            ],
        ),
    ]
