# Generated by Django 5.2.3 on 2025-07-12 04:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='Profile Completed')),
                ('is_document_uploaded', models.BooleanField(default=False, verbose_name='Document Uploaded')),
                ('completed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Completed At')),
            ],
        ),
    ]
