# Generated by Django 5.2.3 on 2025-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
    ]
