# Generated by Django 5.2.3 on 2025-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_participant_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Mobility_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Mobility Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='aids_equipment_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Aids & Equipment Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='behaviour_management_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Behaviour Management Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='chores_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Chores Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='clothing_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Clothing Size'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='communication_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Communication Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='community_access_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Community Access Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='companion_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Companion Card Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='complex_health_support_plan_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Complex Health Support Plan Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dietary_requirements',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dietary Requirements'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dislikes',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='distinguishing_features',
            field=models.TextField(blank=True, null=True, verbose_name='Distinguishing Features'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dressing_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dressing Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='eating_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Eating Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='education_or_employment_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Education/Employment Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='eye_colour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eye Colour'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='food_preparation_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Food Preparation Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='friendships_or_relationships_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Friendships/Relationships Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='getting_drinks_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Getting Drinks Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hair_colour',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hair Colour'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='handling_money_or_budgeting_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Handling Money/Budgeting Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='healthcare_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Healthcare Card Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hobbies_interests',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Hobbies/Interests'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hobbies_or_activities_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Hobbies/Activities Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='home_safety_and_security_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Home Safety & Security Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='learning_new_skills_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Learning New Skills Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level_assistance_required',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Leve of Assistance Required'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='likes',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medical_condition',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Medical Condition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medical_food_other_allergies',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Medical, Food or Other Allergies'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medicare_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medicare Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medication_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Medication Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='menstrual_management_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Menstrual Management Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name_of_doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='opg_guardian_consent_required_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='OPG/Guardian Consent Required Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='other_needs_and_support_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Other Needs and Support Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pension_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pension Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pension_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pension Type'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='personal_or_road_safety_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Personal/Road Safety Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pet_care_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Pet Care Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='private_insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Private Insurance Number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='private_insurance_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Private Insurance Type'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='public_trustee_or_financial_administrator_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Public Trustee/Financial Administrator Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='religion_or_culture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religion or Culture'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='restrictive_practices_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Restrictive Practices Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='shoe_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=20, null=True, verbose_name='Shoe Size'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='showering_or_bathing_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Showering/Bathing Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='spoken_language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spoken Language'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='supports_required',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Supports Required'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='toileting_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Toileting Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='transport_or_travel_details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Transport/Travel Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='unsupported_time_details',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Unsupported Time Details'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
    ]
