# Generated by Django 5.2.3 on 2025-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_participant_mobility_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='guardian_email',
            field=models.EmailField(default='john_doe@gmail.com', max_length=254, verbose_name='Guardian Email'),
        ),
    ]
