# Generated by Django 5.2.3 on 2025-07-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
