# Generated by Django 5.2.3 on 2025-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Client Admin'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer')], default='STAFF', max_length=30, verbose_name='Role'),
        ),
    ]
