# Generated by Django 5.2.3 on 2025-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('zoho_request_id', models.CharField(blank=True, max_length=100)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
