# Generated by Django 5.2.3 on 2025-07-08 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('SENT_FOR_SIGNATURE', 'Sent'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined')], max_length=30)),
                ('pandadoc_document_id', models.CharField(blank=True, max_length=100)),
                ('pandadoc_signing_url', models.URLField(blank=True)),
                ('client_name', models.CharField(max_length=200)),
                ('ndis_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
