# Generated by Django 5.2.3 on 2025-07-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceagreement',
            name='able_swim',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True, verbose_name='Able to Swim'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='can_participate_in_water',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Participate in Water Based Activities'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='casa_staff_call_emergency_service',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Casa Staff Call Emergency Service'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='casa_staff_provide_water_activity',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Casa Staff Provide Water Based Activity'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='casa_staff_share_information',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Casa Staff Share Information'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='client_additional_comments',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Client Additional Comments'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='client_signed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Client Signed Date'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='current_complex_health_support_plan',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Current Complex Health Support Plan'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='day_time_frequency',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Day/Time Frequency'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], null=True, verbose_name='Energy Level'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='guardian_signed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guardian Signed Date'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='informed_refusal_consent',
            field=models.TextField(blank=True, null=True, verbose_name='Informed Refusal Consent'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='like_water',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True, verbose_name='Like Water'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='owner_additional_comments',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Owner Additional Comments'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='owner_name',
            field=models.CharField(default='Anju Isenth', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='owner_signed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Owner Signed Date'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='safe_participate_in_water',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Safe to Participate in Water Based Activities'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='safe_water',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True, verbose_name='Safe Water'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='support_ratio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Support Ratio'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='swimming_skill_level',
            field=models.CharField(blank=True, choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], null=True, verbose_name='Swimming Skill Level'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='tire_easily',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True, verbose_name='Tire Easily'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='two_more_staff',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], null=True, verbose_name='Two More Staff'),
        ),
    ]
