# Generated by Django 5.2.3 on 2025-07-04 11:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_model_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
