# Generated by Django 5.2.3 on 2025-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_loginattempt_auditlog_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='phone',
        ),
        migrations.AddField(
            model_name='user_model',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
    ]
