# Generated by Django 5.2.3 on 2025-07-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_model_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='slug',
        ),
    ]
