# Generated by Django 5.2.3 on 2025-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
