# Generated by Django 5.2.3 on 2025-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_model_phone_user_model_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password'),
        ),
    ]
