# Generated by Django 5.2.3 on 2025-07-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_model_is_active_alter_user_model_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='state_territory',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='suburb',
        ),
    ]
